### ISSUE TITLE
Coupled too much with apache-confs

### ISSUE THREAD

**Issue by ParthKolekar** [nisargjhaveri/minimalMVC#1]

**Comment by nisargjhaveri** [comment]
As in? The `.htaccess` files?

**Comment by ParthKolekar** [comment]
Just remembered the nginx re-write rule which would emulate the .htaccess.
Actually by coupled, I meant that not enough support for nginx. But then, the 'real coders' would figure out the rule. :grin:

**Comment by nisargjhaveri** [comment]
Haha! But there is not even apache re-write rules in this repo.

The `.htaccess` files are just for securing the `sys/` and `app/` from outside access. It is extra measure taken. The framework works perfectly without it, too.
