### ISSUE TITLE
Possible vulnerability in router

### ISSUE THREAD

**Issue by polybuildr** [nisargjhaveri/minimalMVC#2]
While talking in the [PHP stackoverflow room](http://chat.stackoverflow.com/rooms/11/php), one of the users pointed out a possible vulnerability in `sys/router.php`.

Since you're splitting the path on `/` and PHP interprets `\` the same way, there is a chance that the user can execute arbitrary PHP files by using `\`s in the URL.

**Comment by nisargjhaveri** [comment]
So, I looked at it. Looks like doesn't really harm much. Please check if I've missed something.

Also see 3824c9c24760a6a4ffe8177b21b015ee2056ea0f.
